#!/bin/bash
set -u

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

app=$YNH_APP_INSTANCE_NAME
domain=$(ynh_app_setting_get $app domain)

sudo rm -rf /var/www/rocketchat

sudo rm -f /etc/nginx/conf.d/$domain.d/rocketchat.conf
sudo rm -Rf /var/log/rocketchat/
sudo systemctl stop Rocketchat.service
sudo rm /etc/systemd/system/Rocketchat.service
sudo systemctl restart nginx
