#!/bin/bash
set -eu

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source ./_common.sh
source /usr/share/yunohost/helpers

ynh_abort_if_errors

app=$YNH_APP_INSTANCE_NAME
final_path=$(ynh_app_setting_get $app final_path)
serviceuser=$(ynh_app_setting_get $app serviceuser)
path=$(ynh_app_setting_get $app path)
port=$(ynh_app_setting_get $app port)

#=================================================
# BACKUP THE APPLICATION
#=================================================

# Backup the current version of the app
ynh_backup_before_upgrade > >(tee "upgrade.log")

sudo systemctl stop rocketchat

sudo rm -rf $final_path
sudo mkdir -p $final_path

# update to latest required node setup
installnode

ynh_setup_source "$final_path"

sudo chown -R $serviceuser: $final_path

cd $final_path/programs/server/
sudo npm install --production

sudo chown -R $serviceuser: $final_path

sudo systemctl start rocketchat
waitforservice
